# Generated by Django 5.1.3 on 2024-11-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("corretor", models.CharField(blank=True, max_length=255, null=True)),
                ("digitador", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "codigo_loja",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("sala", models.CharField(blank=True, max_length=255, null=True)),
                ("contrato", models.CharField(blank=True, max_length=255, null=True)),
                ("cliente", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "cpf_do_cliente",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
                (
                    "rg_do_cliente",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "nome_da_mae",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                ("cep", models.CharField(blank=True, max_length=10, null=True)),
                ("cidade", models.CharField(blank=True, max_length=100, null=True)),
                ("uf", models.CharField(blank=True, max_length=2, null=True)),
                ("matricula", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "especie_do_beneficio",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "uf_do_beneficio",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "salario",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "telefone_residencial",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "telefone_comercial",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "telefone_celular",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("recebe_beneficio_cartao", models.BooleanField(default=False)),
                ("contrato_portado", models.BooleanField(default=False)),
                ("ade", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "ade_vinculada",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tipo_pagamento",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("banco", models.CharField(blank=True, max_length=100, null=True)),
                ("agencia", models.CharField(blank=True, max_length=10, null=True)),
                ("dv_agencia", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "numero_conta",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("dv_conta", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "tipo_de_conta",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "banco_emprestimo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "orgao_convenio",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("operacao", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "status_do_contrato",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("formalizacao_digital", models.BooleanField(default=False)),
                ("pendente_de_formalizacao", models.BooleanField(default=False)),
                ("link_formalizacao", models.URLField(blank=True, null=True)),
                (
                    "data_da_digitacao_do_contrato_no_banco",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "data_da_digitacao_do_contrato_no_sistema",
                    models.DateField(blank=True, null=True),
                ),
                ("data_de_pagamento", models.DateField(blank=True, null=True)),
                ("data_pagamento_do_saldo", models.DateField(blank=True, null=True)),
                (
                    "data_de_despacho_do_beneficio",
                    models.DateField(blank=True, null=True),
                ),
                ("tabela", models.CharField(blank=True, max_length=50, null=True)),
                ("prazo", models.IntegerField(blank=True, null=True)),
                (
                    "producao_bruta",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "producao_bruta_com_ajuste",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "producao_liquida",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "producao_liquida_com_ajuste",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("cliente_novo", models.BooleanField(default=False)),
                (
                    "total_valor_parcelas",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("clonado", models.BooleanField(default=False)),
                (
                    "valor_operacao_operacional",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "valor_cliente_operacional",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "valor_parcela_operacional",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("origem", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "valor_base",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "valor_base_com_ajuste",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "banco_origem_nome_1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("banco_origem_prazo_1", models.IntegerField(blank=True, null=True)),
                (
                    "banco_origem_parcelas_pagas_1",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "banco_origem_valor_parcela_1",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "banco_origem_valor_quitacao_1",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("observacao", models.TextField(blank=True, null=True)),
                (
                    "caixa_do_contrato",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("sexo", models.CharField(blank=True, max_length=1, null=True)),
                ("data_da_formalizacao", models.DateField(blank=True, null=True)),
                ("previsao_chegada_saldo", models.DateField(blank=True, null=True)),
                (
                    "tipo_chave_pix",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("chave_pix", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.CharField(default="Novo", max_length=50)),
                (
                    "valor_saldo",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("data_inclusao", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
