# Generated by Django 5.1.3 on 2024-11-15 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contrato",
            name="ade_vinculada",
        ),
    ]
