# Generated by Django 5.1.3 on 2024-11-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_remove_contrato_ade_vinculada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="banco_origem_valor_parcela_1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="banco_origem_valor_quitacao_1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="producao_bruta",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="producao_bruta_com_ajuste",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="producao_liquida",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="producao_liquida_com_ajuste",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="salario",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="total_valor_parcelas",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="valor_base",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="valor_base_com_ajuste",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="valor_cliente_operacional",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="valor_operacao_operacional",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="valor_parcela_operacional",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="valor_saldo",
            field=models.FloatField(default=0.0),
        ),
    ]
