# myapp/models.py

from django.db import models

class Contrato(models.Model):
    # Campos baseados nas colunas fornecidas
    corretor = models.CharField(max_length=255, blank=True, null=True)
    digitador = models.CharField(max_length=255, blank=True, null=True)
    codigo_loja = models.CharField(max_length=255, blank=True, null=True)
    sala = models.CharField(max_length=255, blank=True, null=True)
    contrato = models.CharField(max_length=255, blank=True, null=True)
    cliente = models.CharField(max_length=255, blank=True, null=True)
    cpf_do_cliente = models.CharField(max_length=14, blank=True, null=True)
    rg_do_cliente = models.CharField(max_length=20, blank=True, null=True)
    nome_da_mae = models.CharField(max_length=255, blank=True, null=True)
    data_nascimento = models.DateField(blank=True, null=True)
    cep = models.CharField(max_length=10, blank=True, null=True)
    cidade = models.CharField(max_length=100, blank=True, null=True)
    uf = models.CharField(max_length=2, blank=True, null=True)
    matricula = models.CharField(max_length=255, blank=True, null=True)
    especie_do_beneficio = models.CharField(max_length=255, blank=True, null=True)
    uf_do_beneficio = models.CharField(max_length=2, blank=True, null=True)
    salario = models.FloatField(blank=True, null=True)
    telefone_residencial = models.CharField(max_length=20, blank=True, null=True)
    telefone_comercial = models.CharField(max_length=20, blank=True, null=True)
    telefone_celular = models.CharField(max_length=20, blank=True, null=True)
    recebe_beneficio_cartao = models.BooleanField(default=False)
    contrato_portado = models.BooleanField(default=False)
    ade = models.CharField(max_length=255, blank=True, null=True)
    tipo_pagamento = models.CharField(max_length=50, blank=True, null=True)
    banco = models.CharField(max_length=100, blank=True, null=True)
    agencia = models.CharField(max_length=10, blank=True, null=True)
    dv_agencia = models.CharField(max_length=5, blank=True, null=True)
    numero_conta = models.CharField(max_length=20, blank=True, null=True)
    dv_conta = models.CharField(max_length=5, blank=True, null=True)
    tipo_de_conta = models.CharField(max_length=50, blank=True, null=True)
    banco_emprestimo = models.CharField(max_length=100, blank=True, null=True)
    orgao_convenio = models.CharField(max_length=100, blank=True, null=True)
    operacao = models.CharField(max_length=50, blank=True, null=True)
    status_do_contrato = models.CharField(max_length=50, blank=True, null=True)
    formalizacao_digital = models.BooleanField(default=False)
    pendente_de_formalizacao = models.BooleanField(default=False)
    link_formalizacao = models.URLField(blank=True, null=True)
    data_da_digitacao_do_contrato_no_banco = models.DateField(blank=True, null=True)
    data_da_digitacao_do_contrato_no_sistema = models.DateField(blank=True, null=True)
    data_de_pagamento = models.DateField(blank=True, null=True)
    data_pagamento_do_saldo = models.DateField(blank=True, null=True)
    data_de_despacho_do_beneficio = models.DateField(blank=True, null=True)
    tabela = models.CharField(max_length=50, blank=True, null=True)
    prazo = models.IntegerField(blank=True, null=True)
    producao_bruta = models.FloatField(blank=True, null=True)
    producao_bruta_com_ajuste = models.FloatField(blank=True, null=True)
    producao_liquida = models.FloatField(blank=True, null=True)
    producao_liquida_com_ajuste = models.FloatField(blank=True, null=True)
    cliente_novo = models.BooleanField(default=False)
    total_valor_parcelas = models.FloatField(blank=True, null=True)
    clonado = models.BooleanField(default=False)
    valor_operacao_operacional = models.FloatField(blank=True, null=True)
    valor_cliente_operacional = models.FloatField(blank=True, null=True)
    valor_parcela_operacional = models.FloatField(blank=True, null=True)
    origem = models.CharField(max_length=100, blank=True, null=True)
    valor_base = models.FloatField(blank=True, null=True)
    valor_base_com_ajuste = models.FloatField(blank=True, null=True)
    banco_origem_nome_1 = models.CharField(max_length=100, blank=True, null=True)
    banco_origem_prazo_1 = models.IntegerField(blank=True, null=True)
    banco_origem_parcelas_pagas_1 = models.IntegerField(blank=True, null=True)
    banco_origem_valor_parcela_1 = models.FloatField(blank=True, null=True)
    banco_origem_valor_quitacao_1 = models.FloatField(blank=True, null=True)
    observacao = models.TextField(blank=True, null=True)
    caixa_do_contrato = models.CharField(max_length=100, blank=True, null=True)
    sexo = models.CharField(max_length=1, blank=True, null=True)
    data_da_formalizacao = models.DateField(blank=True, null=True)
    previsao_chegada_saldo = models.DateField(blank=True, null=True)
    tipo_chave_pix = models.CharField(max_length=50, blank=True, null=True)
    chave_pix = models.CharField(max_length=100, blank=True, null=True)
    # Campos adicionais
    status = models.CharField(max_length=50, default='Novo')
    valor_saldo = models.FloatField(default=0.0)
    data_inclusao = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.cliente} - {self.contrato}"
